apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: devops-practice1
        image: juanphozm/devopspracticejuan:latest
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp
  namespace: default
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31328
     
